# vi: ft=ruby
# Configuration Management
brew 'stow'

# Shell
brew 'fish'
brew 'starship'
brew 'atuin'
brew 'direnv'

# Shell Utilities
brew 'ag'
brew 'diff-so-fancy'
brew 'fzf'
brew 'gh'
brew 'gnu-sed'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'z'

# Editors
tap 'neovim/neovim'
brew 'neovim'

# Personal Taps
tap 'blamattina/formulae'

# Formatting
brew 'prettierd'
brew 'stylua'

# Linting
brew 'eslint_d'
brew 'ruff'
brew 'shellcheck'
brew 'selene'

# Casks
cask '1password'
cask 'bartender'
cask 'ghostty'
cask 'font-sauce-code-pro-nerd-font'
cask 'iterm2'
cask 'lunar'
cask 'macwhisper'
cask 'mouser'
cask 'obsidian'
cask 'raycast'
cask 'rectangle'
cask 'steermouse'
