#!/bin/bash

print_message() {
  echo "🤘 $@"
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_DIR=${DIR/\/scripts/}

print_message "Unlinking dotfiles..."
stow --dotfiles --target="$HOME" --dir="$DOTFILES_DIR" --delete .
